# Generated by Django 5.0.3 on 2024-03-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_title', models.CharField(max_length=255)),
                ('Book_price', models.CharField(max_length=255)),
                ('Book_type', models.CharField(choices=[('Thirller', 'Thirller'), ('Rom-Com', 'Rom-Com'), ('Mystery', 'Mystery'), ('Motivational', 'Motivational')], max_length=20)),
                ('Book_Author', models.CharField(max_length=255)),
                ('About', models.TextField()),
            ],
        ),
    ]
